behaviors:
  PlayerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 10000
    self_play:
      window: 10  # Number of past versions stored for self-play
      play_against_latest_model_ratio: 0.5  # 50% of the time, play against the latest model
      save_steps: 50000  # Save model every X steps
      swap_steps: 200000  # How often to swap opponents